name: climate

dependencies:
  - python=3.6.9
  - pandas=0.25.0
  - numpy=1.16.4
  - matplotlib=3.1.1
  - jupyter
  - ipykernel
  - r=3.6.1
  - dplyr=0.8.0.1
  - plotly=4.9.1
  - r2d3=0.2.3
  - shiny=1.3.2
  - shinyjs=1.0
  - shinythemes=1.1.2
 
