name: climate

dependencies:
  - python=3.6.9
  - pandas=0.25.0
  - numpy=1.16.4
  - matplotlib=3.1.1
  - jupyter
  - ipykernel
  - r-base=3.6.1
  - r-dplyr=0.8.0.1
  - rstudio
  - r-plotly
  - r-r2d3=0.2.3
  - r-shiny=1.3.2
  - r-shinyjs=1.0
  - r-shinythemes=1.1.2