name: climate

dependencies:
  - python=3.6.9
  - pandas=0.25.3
  - numpy=1.17.4
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - scikit-learn=0.21.3
  - scipy=1.3.0
  - jupyter
  - ipykernel
  - nb_conda
  - r-base=3.6.1
  - r-dplyr=0.8.0.1
  - rstudio
  - r-plotly
  - r-r2d3=0.2.3
  - r-shiny=1.3.2
  - r-shinyjs=1.0
  - r-shinythemes=1.1.2
  - pip
  - pip:
      - pygam